export * as AuthenQuery from './authen'
export * as ConfigurationQuery from './configuration'
export * as MasterConfigQuery from './masterConfig'
export * as ResourcesQuery from './resources'
export * as TermsAndConditionsQuery from './termsAndConditions'
export * as TransactionsQuery from './transactions'
