export enum DomainErrorCode {
	INVALID_CONTENT = 'invalidContent',
	NOT_FOUND = 'notFound',
	UNKNOWN = 'unknown',
	UNAUTHORIZED = 'unAuthorized',
	FORBIDDEN = 'forbidden',
	METHOD_NOT_ALLOWED = 'methodNotAllowed',
	NOT_ACCEPTABLE = 'notAcceptable',
	INTERNAL_SERVER_ERROR = 'internalServerError',
	BAD_GATEWAY = 'badGateway',
	SERVICE_UNAVAILABLE = 'serviceUnavailable',
	GATEWAY_TIMEOUT = 'gatewayTimeout',
}

export enum StatusCode {
	BAD_REQUEST = '400',
	UNAUTHORIZED = '401',
	FORBIDDEN = '403',
	NOT_FOUND = '404',
	METHOD_NOT_ALLOWED = '405',
	NOT_ACCEPTABLE = '406',
	INTERNAL_SERVER_ERROR = '500',
	BAD_GATEWAY = '502',
	SERVICE_UNAVAILABLE = '503',
	GATEWAY_TIMEOUT = '504',
}

export enum PmtStatusCode {
	PMT_1000 = 'PMT-1000',
	PMT_2009 = 'PMT-2009',
	PMT_2014 = 'PMT-2014',
	PMT_2015 = 'PMT-2015',
	PMT_2016 = 'PMT-2016',
	PMT_2007 = 'PMT-2007',
	PMT_4011 = 'PMT-4011',
}

export enum ErrorType {
	EXTERNAL_ERROR = 'externalError',
	SOMETHING_WENT_WRONG = 'somethingWentWrong',
	DATA_NOT_FOUND = 'dataNotFound',
	DATA_NOT_FOUND_NOT_IN_WHITELIST = 'dataNotFoundNotInWhitelist',
	DATA_NOT_FOUND_IN_WHITELIST = 'dataNotFoundInWhitelist',
	DATA_DUPLICATE_EXISTS = 'dataDuplicateExists',
	OWNER_APPROVE = 'ownerApprove',
	STATUS_IS_WRONG = 'statusIsWrong',
	CANT_CONNECT_CORE = 'cannotConnectCore',
	TASK_STATUS_WRONG = 'taskStatusWrong',
	DATA_ALREADY_EXISTS = 'dataAlreadyExists',
	INVALID_INFORMATION = 'invalidInformation',
}

export enum TaskMonitoringErrorCode {
	TASK_STATUS_ERROR = '4033',
	TASK_NAME_ERROR = '4072',
	DATA_NOT_FOUND = '4015',
	CANNOT_CONNECT_CIS_CORE = '9100',
	ANY_ERROR = '9300',
}

export interface IErrors {
	row: string
	message: string
}

export interface IBuildAPIErrorPayload {
	status: string
	code: string
	message: string
	fields?: any
	data?: unknown
}

export enum BusinessCode {
	// 200
	SUCCESS = 1000,
	SUCCESSFULLY_UPDATED_INFORMATION = 1001,
	// 400
	BAD_REQUEST_PARAMETER_BODY = 2001,
	ACCOUNT_MAPPING_SAME_AS_CURRENT_MAPPING = 2002,
	// 200
	DATA_NOT_FOUND = 3000,
	USER_PASSWORD_INCORRECT = 3001,
	DATA_ALREADY_EXISTS = 3002,
	CANNOT_UPDATE_USER = 3003,
	ACCESS_DENIED = 3004,
	CANNOT_UPDATE_DATA_OR_STATUS = 3005,
	CANNOT_UPDATE_STATUS_TRADING_ACCOUNT_NO_IS_NOT_EMPTY = 3006,
	// 409
	CANNOT_UPDATE_CUSTOMER_INFOMATION_CUSTOMER_DOSE_NOT_EXISTS = 4001,
	CANNOT_UPDATE_CUSTOMER_INFOMATION_MICROSERVICE_INTERNAL_ERROR = 4002,
	CANNOT_UPDATE_CIS_CUSTOMER_INFOMATION_CUSTOMER_HAS_PROCESSING = 4003,
	CANNOT_UPDATE_CIS_CUSTOMER_INFOMATION_MICROSERVICE_INTERNAL_ERROR = 4004,
	CANNOT_UPDATE_CIS_CUSTOMER_INFOMATION_MORE_THAN_ONE_CIS_UID_IS_FOUND = 4005,
	CANNOT_UPDATE_CUSTOMER_INFOMATION_BAD_REQUEST_PARAMETER = 4006,
	CANNOT_UPDATE_CIS_CUSTOMER_INFOMATION_BAD_REQUEST_PARAMETER = 4007,
	CANNOT_UPDATE_CIS_CUSTOMER_INFOMATION_MORE_THAN_ONE_CUSTOMER_ID_IS_FOUND = 4008,
	// 500
	CANNOT_CONNECT_TO_DATABASE = 9000,
	CANNOT_MAKE_CHANGE_TO_DATABASE = 9001,
	CANNOT_CONNECT_TO_CIS_INTERNAL_MICROSERVICE = 9100,
	UNEXPECTED_ERROR_OCCURRED = 9300,
	CANNOT_UPLOAD_FILE_TO_S3 = 9400,
}
