apiVersion: v1
kind: Service
metadata:
  labels:
    app: ##SERVICE_NAME##
  name: ##SERVICE_NAME##
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: ##SERVICE_NAME##